# Generated by Django 2.2.16 on 2021-07-23 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sort_order', models.IntegerField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('display_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PressItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete='models.CASCADE', related_name='press_items', to='press.Category')),
                ('media_type', models.ForeignKey(on_delete='models.CASCADE', related_name='press_items', to='press.MediaType')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='press.Venue')),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
