# Generated by Django 2.2.16 on 2020-10-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='book_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='publisher',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
