# Generated by Django 2.2.16 on 2020-10-24 17:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('word_count', models.IntegerField()),
                ('issue', models.CharField(blank=True, max_length=200)),
                ('piece_url', models.URLField(null=True)),
                ('pull_quote', models.TextField()),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('cover_image', models.ImageField(null=True, upload_to='covers/')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200, null=True)),
                ('review_url', models.URLField()),
                ('review_venue', models.CharField(max_length=200)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('review_pull_quote', models.CharField(max_length=200, null=True)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shorts.Piece')),
            ],
        ),
        migrations.AddField(
            model_name='piece',
            name='published_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shorts.Publisher'),
        ),
    ]
