# Generated by Django 2.1 on 2020-11-01 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece_type', models.CharField(choices=[('story', 'Short Story'), ('poem', 'Poem'), ('essay', 'Essay'), ('article', 'Article')], default='story', max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('word_count', models.IntegerField()),
                ('issue', models.CharField(blank=True, max_length=200)),
                ('piece_url', models.URLField(blank=True)),
                ('audio_url', models.URLField(blank=True)),
                ('pull_quote', models.TextField()),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('pending_date', models.DateField(blank=True, null=True)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('cover_url', models.URLField(blank=True, null=True)),
                ('genre', models.ManyToManyField(related_name='pieces', to='shorts.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=200)),
                ('review_url', models.URLField()),
                ('review_venue', models.CharField(max_length=200)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('review_pull_quote', models.CharField(blank=True, max_length=200)),
                ('text_for_archive', models.TextField(blank=True, null=True)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shorts.Piece')),
            ],
        ),
        migrations.AddField(
            model_name='piece',
            name='published_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shorts.Publisher'),
        ),
    ]
