# Generated by Django 2.2.16 on 2020-11-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0002_remove_piece_cover_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers'),
        ),
    ]
