# Generated by Django 2.2.16 on 2020-10-25 08:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0002_remove_piece_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='published_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
