# Generated by Django 2.2.16 on 2020-10-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0003_piece_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='created_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='piece',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
