# Generated by Django 2.2.16 on 2020-11-01 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0003_piece_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piece',
            name='cover',
        ),
    ]
