# Generated by Django 2.2.16 on 2020-11-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0004_remove_piece_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='cover',
            field=models.URLField(blank=True, null=True),
        ),
    ]
