# Generated by Django 2.2.16 on 2020-10-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0004_auto_20201025_0410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='piece',
            name='piece_type',
            field=models.CharField(choices=[('story', 'Short Story'), ('poem', 'Poem'), ('essay', 'Essay'), ('article', 'Article')], default='story', max_length=200),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
