# Generated by Django 2.2.16 on 2021-04-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0005_piece_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='cover_upload',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
