# Generated by Django 2.2.16 on 2020-10-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0005_auto_20201025_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='genre',
            field=models.ManyToManyField(related_name='pieces', to='shorts.Genre'),
        ),
    ]
