# Generated by Django 2.2.16 on 2020-10-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0006_piece_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piece',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='piece',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers'),
        ),
    ]
