# Generated by Django 2.2.16 on 2021-04-10 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0006_piece_cover_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piece',
            name='cover',
        ),
    ]
