# Generated by Django 2.2.16 on 2021-07-18 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0007_remove_piece_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='genre',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='piece',
            name='piece_type',
        ),
        migrations.AddField(
            model_name='piece',
            name='category',
            field=models.ManyToManyField(related_name='pieces', to='shorts.Category'),
        ),
    ]
