# Generated by Django 2.2.16 on 2020-10-25 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0007_auto_20201025_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='genre',
            new_name='name',
        ),
    ]
