# Generated by Django 2.2.16 on 2020-10-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0008_auto_20201025_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='text_for_archive',
            field=models.TextField(blank=True, null=True),
        ),
    ]
