# Generated by Django 2.2.16 on 2021-07-18 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0008_auto_20210717_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piece',
            name='category',
        ),
        migrations.AddField(
            model_name='piece',
            name='category',
            field=models.ForeignKey(null=True, on_delete=models.CASCADE, related_name='pieces', to='shorts.Category'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='pull_quote',
            field=models.TextField(blank=True),
        ),
    ]
