# Generated by Django 2.2.16 on 2020-10-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0009_review_text_for_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='audio_url',
            field=models.URLField(blank=True),
        ),
    ]
