# Generated by Django 2.2.16 on 2021-07-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0009_auto_20210717_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sort_order',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
