# Generated by Django 2.2.16 on 2021-07-18 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0010_category_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='piece',
            options={'ordering': ['-pending_date', '-published_date']},
        ),
    ]
