# Generated by Django 2.2.16 on 2021-07-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0011_auto_20210718_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='pieces', to='shorts.Genre'),
        ),
    ]
