# Generated by Django 2.2.16 on 2022-01-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0012_auto_20210718_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='piece',
            options={},
        ),
        migrations.AddField(
            model_name='piece',
            name='status',
            field=models.CharField(choices=[('PUB', 'Published'), ('PEN', 'Pending')], default='PEN', max_length=10),
        ),
    ]
