# Generated by Django 2.2.16 on 2020-10-28 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0013_genre_slug_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='slug_field',
        ),
    ]
