# Generated by Django 2.2.16 on 2020-10-28 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0014_remove_genre_slug_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
