# Generated by Django 2.2.16 on 2020-11-01 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0015_genre_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piece',
            name='cover',
        ),
    ]
